name: build-push

on:
  push:
    branches:
      - 'master'

jobs:
  docker_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Status
        uses: crazy-max/ghaction-docker-status@v1

  build:
    runs-on: ubuntu-latest
    needs: docker_status
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: buluma/setup-buildx-action@0.1.0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false

  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: buluma/setup-buildx-action@0.1.0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: true
          # platforms: linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v6
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/arm64,linux/riscv64,linux/ppc64le,linux/arm/v7
          tags: buluma/github-action-graphviz:${{ env.tag }}
          # tags: buluma/github-action-graphviz:${{ env.tag }}
